### ISSUE TITLE
Feature request: Multiple pages

### ISSUE THREAD

**Issue by udurraniAtPresage** [kennedymwavu/micromodal#5]
Thank you for this awesome package. Could you support multiple pages like screens from the shinyglide package?

**Comment by kennedymwavu** [comment]
Hi @udurraniAtPresage 
You can use shinyglide screens inside micromodal.

**Comment by udurraniAtPresage** [comment]
Thank you for your response. That is a good option. 

I also realized that I can use `data-micromodal-trigger` and `data-micromodal-close = NA` in the same button that can close the current modal and also trigger another modal!

**Comment by kennedymwavu** [comment]
Yes. I should probably include that in the docs.
